### ISSUE TITLE
ERRORS IN ./install CODE LINES

### ISSUE THREAD

**Issue by githubkill202** [Cyber-Guy1/BlackDragon#6] opened 2021-05-25 22:35 UTC
Cloning into 'Sublist3r'...
remote: Enumerating objects: 383, done.
remote: Total 383 (delta 0), reused 0 (delta 0), pack-reused 383
Receiving objects: 100% (383/383), 1.12 MiB | 1.24 MiB/s, done.
Resolving deltas: 100% (212/212), done.
WARNING: Keyring is skipped due to an exception: Failed to open keyring: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocke

 ./install: line 254: cd: /root/BD-Tools/asnlookup: No such file or directory
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'                                                                    
./install: line 258: cd: /root/BlackDragon/BD-Tools/: No such file or directory

Installing HTTProbe 

./install: line 262: go: command not found

 Installing unfurl 

./install: line 266: go: command not found

 Installing Waybackurls 

./install: line 270: go: command not found

AFTER INSTALLATION BUGS:

---------------------------------------------
          Subfinder Is Starting ...                  
---------------------------------------------

./Black-Dragon: line 116: subfinder: command not found

---------------------------------------------
          Asset Finder Is Starting ...                  
---------------------------------------------

./Black-Dragon: line 122: assetfinder: command not found

---------------------------------------------
          Sublist3r Is Starting ...                  
---------------------------------------------

python3: can't open file '/root/BlackDragon/BD-Tools/Sublist3r/sublist3r.py': [Errno 2] No such file or directory

  Github Subdomain Gathering Is Starting ...                  
---------------------------------------------

Do You Have Github Token ?

[1] Yes
[2] No
[-] Press Enter To Skip

{root}@Black-Dragon: 1

 Choise Is Out Of Range ] Exiting ...

---------------------------------------------
               Amass [intel] ...                  
---------------------------------------------

Do You Want To Run Amass [intel] Scan [May Take Some Time] ?

[1] Yes
[2] No
[-] Press Enter To Skip

{root}@Black-Dragon: 1
/usr/bin/amass: 1: G@p@8: not found
/usr/bin/amass: 2: @ not found
/usr/bin/amass: 3:����o: not found
/usr/bin/amass: 1: ELF: not found
/usr/bin/amass: 4:▒xf�fgpp: not found
/usr/bin/amass: 5: Syntax error: "(" unexpected

---------------------------------------------
               Amass [enum] ...                  
---------------------------------------------

Do You Want To Run Amass [enum] Scan [May Take Some Time] ?

[1] Yes
[2] No
[-] Press Enter To Skip

{root}@Black-Dragon: 1
./Black-Dragon: line 236: /usr/bin/amass: cannot execute binary file: Exec format error

---------------------------------------------
        Live Subdomain Filtering ...                  
---------------------------------------------

Do You Want To Filter The Live Subdomains ?

[1] Yes
[2] No
[-] Press Enter To Skip

{root}@Black-Dragon: 1
./Black-Dragon: line 267: httprobe: command not found
cat: knockpy-fast: Is a directory

====================================
     DNS Information Gathering                  
====================================

---------------------------------------------
            DNSMap Is Starting ...                  
---------------------------------------------

./Black-Dragon: line 295: dnsmap: command not found

**Comment by Cyber-Guy1** [comment] 2021-05-25 22:37
Did You Run The Script As Root ?

**Comment by githubkill202** [comment] 2021-05-25 22:41
keep up the good work!

**Comment by Cyber-Guy1** [comment] 2021-05-25 22:46
Thanks!

**Comment by Cyber-Guy1** [comment] 2021-05-25 22:46
So There Is No Problem RN ?!

**Comment by githubkill202** [comment] 2021-05-25 23:12
if i dont run it as root was other issues.

**Comment by githubkill202** [comment] 2021-05-25 23:13
no there are the issues listed and if u want i write also the problem i find running it without root

**Comment by Cyber-Guy1** [comment] 2021-05-25 23:13
What Is It ?

**Comment by githubkill202** [comment] 2021-05-25 23:14
when u run ./install without root he cant create directory even with chmod on. if u run it with root u got the issues listed.

**Comment by githubkill202** [comment] 2021-05-25 23:14
i make another check.

**Comment by githubkill202** [comment] 2021-05-25 23:16
./Black-Dragon: line 122: assetfinder: command not found
tee: assestfinder.txt: Permission denied
WITHOUT "SUDO"

**Comment by githubkill202** [comment] 2021-05-25 23:17
running ./install without root got permission errors anyway. (CHMOD ON)

**Comment by githubkill202** [comment] 2021-05-25 23:19
probably is syntax errors in ./install line codes.254 258 262 266 270

**Comment by githubkill202** [comment] 2021-05-25 23:22
WITHOUT ROOT---------------------------------------------
               Amass [intel] ...                  
---------------------------------------------

Do You Want To Run Amass [intel] Scan [May Take Some Time] ?

[1] Yes
[2] No
[-] Press Enter To Skip

{n3xtg3n}@Black-Dragon: 1
[sudo] password for n3xtg3n: 
/usr/bin/amass: 1: G@p@8: not found
/usr/bin/amass: 2: @ not found
/usr/bin/amass: 3:����o: not found
/usr/bin/amass: 1: ELF: not found
/usr/bin/amass: 4:▒xf�fgpp: not found
/usr/bin/amass: 5: Syntax error: "(" unexpected

**Comment by githubkill202** [comment] 2021-05-25 23:26
WITHOUT ROOT

@Black-Dragon: 1
./Black-Dragon: line 236: /usr/bin/amass: cannot execute binary file: Exec format error

**Comment by Cyber-Guy1** [comment] 2021-06-17 13:22
What Linux Distribution You Use ?

**Comment by Cyber-Guy1** [comment] 2021-06-17 17:06
Now I Handled The Error Please Re-Run The Installation Script

**Comment by Cyber-Guy1** [comment] 2021-06-25 20:32
Due not responding i think that the problem is solved now so i'll close the issue.

Thank you

**Closed by Cyber-Guy1** 2021-06-25 20:32 UTC
